In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
print(a1)
print(a2)

[1 2 3 4]
[5 6 7 8]


In [6]:
a3=np.array([]*len(a1))
print(a3)

[]


In [7]:
a3=a1+a2
print(a3)

[ 6  8 10 12]


In [8]:
print(a3*3)

[18 24 30 36]


In [9]:
print(a1&a2)

[1 2 3 0]


In [10]:
print(a1|a2)

[ 5  6  7 12]


In [11]:
print(~a1)

[-2 -3 -4 -5]


In [12]:
print(~a2)

[-6 -7 -8 -9]


In [13]:
print(a1^a2)

[ 4  4  4 12]


In [14]:
print(a1[::-1])

[4 3 2 1]


In [15]:
print(a2[::-1])

[8 7 6 5]


In [16]:
print(a1[1:-1])

[2 3]


In [17]:
print(a2[1:-1])

[6 7]


In [18]:
print(a1==a2)
print(a1>=a2)
print(a1<=a2)
print(a1<a2)
print(a1>a2)

[False False False False]
[False False False False]
[ True  True  True  True]
[ True  True  True  True]
[False False False False]


In [20]:
m1=np.matrix([[1,2,3,20],[4,5,6,21],[7,8,9,22]])
m2=np.matrix([[11,12,13,23],[14,15,16,24],[17,18,19,25]])
print(m1)
print(m2)

[[ 1  2  3 20]
 [ 4  5  6 21]
 [ 7  8  9 22]]
[[11 12 13 23]
 [14 15 16 24]
 [17 18 19 25]]


In [21]:
m3=m1+m2
print(m3)

[[12 14 16 43]
 [18 20 22 45]
 [24 26 28 47]]


In [22]:
print(m3*3)

[[ 36  42  48 129]
 [ 54  60  66 135]
 [ 72  78  84 141]]


In [23]:
print(m1&m2)

[[ 1  0  1 20]
 [ 4  5  0 16]
 [ 1  0  1 16]]


In [24]:
print(m1|m2)

[[11 14 15 23]
 [14 15 22 29]
 [23 26 27 31]]


In [25]:
print(m1^m2)

[[10 14 14  3]
 [10 10 22 13]
 [22 26 26 15]]


In [26]:
print(~m2)

[[-12 -13 -14 -24]
 [-15 -16 -17 -25]
 [-18 -19 -20 -26]]


In [27]:
print(~m1)

[[ -2  -3  -4 -21]
 [ -5  -6  -7 -22]
 [ -8  -9 -10 -23]]


In [28]:
print(m1)

[[ 1  2  3 20]
 [ 4  5  6 21]
 [ 7  8  9 22]]


In [29]:
m1[:][::-1]

matrix([[ 7,  8,  9, 22],
        [ 4,  5,  6, 21],
        [ 1,  2,  3, 20]])

In [30]:
m2[::-1][:]

matrix([[17, 18, 19, 25],
        [14, 15, 16, 24],
        [11, 12, 13, 23]])

In [31]:
m1==m2

matrix([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
m1>=m2

matrix([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [33]:
m1<=m2

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [34]:
m1<m2

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [35]:
m1>m2

matrix([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [38]:
np.reshape(m1,(2,6))

matrix([[ 1,  2,  3, 20,  4,  5],
        [ 6, 21,  7,  8,  9, 22]])

In [45]:
m1=np.resize(m1,(5,5))

In [46]:
m1

array([[ 1,  2,  3, 20,  4],
       [ 5,  6, 21,  7,  8],
       [ 9, 22,  1,  2,  3],
       [20,  4,  5,  6, 21],
       [ 7,  8,  9, 22,  1]])

In [47]:
np.hsplit(m1,2)

ValueError: array split does not result in an equal division